version: "1.0"
services:
    web_app:
      build: ./
      restart: always
      command:
        - npm
        - run
        - dev
      #command: npm run dev
      environment:
        - NODE_ENV=development
      networks:
        - default 
      ports:
        - 8089:8088
        - 9229:9229
      privileged: true
      volumes: 
        - .:/var/www/app
        # - thewall:/var/www/app

volumes:
  thewall: