DATABASE:
  host: 192.168.1.49 #localhost
  user: docker_root #root
  password: root
    # host: host.docker.internal
  #host: 192.168.0.160 #tests
  #user: sv_root
  #password: svroot123
  database: wall_assignment_december
  connectTimeout: 999999

SESSION_NAME: 'secret-session'
SERVER: localhost
PORT: 8088

ENCRYPTION:
  passkey:
    start: 'gha67432sdghag7s23_'
    end: '_ha8762bb'